[package]
name = "lenkeng-receiver"
version = "0.1.0"
authors = ["Hidekazu Kobayashi <hidekazu-kobayashi@cookpad.com>"]
edition = "2018"

[dependencies]
libturbojpeg-sys = { path = "./libturbojpeg-sys" }
